name: actionflow
on:
  push:
    branches:
      - main
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: checkoutrepo
        uses: actions/checkout@v3
      - name: azlogin
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACTION_FLOW }} 

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: RG_SA_Practical
        run: terraform init

      - name: Terraform Plan
        working-directory: RG_SA_Practical
        run: terraform plan
